name: Wakatime Generator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  
jobs:
  update-readme:
    name: Profile Readme Development Stats
    runs-on: ubuntu-latest
    steps:
    #  - name: Get Secrets
    #    uses: bitwarden/sm-action@v2
    #    with:
    #      access_token: ${{ secrets.BW_ACCESS_TOKEN }}
    #      secrets: |
    #        00000000-0000-0000-0000-000000000000 > WAKATIME_API_KEY
    #        00000000-0000-0000-0000-000000000000 > GH_TOKEN

      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: true
          SHOW_LINES_OF_CODE: true
          SHOW_PROFILE_VIEWS: false
          SHOW_EDITORS: true
          SHOW_OS: true
          SHOW_LOC_CHART: false
          SHOW_SHORT_INFO: false
          SHOW_DAYS_OF_WEEK: false
          SHOW_UPDATED_DATE: false
          SHOW_LANGUAGE_PER_REPO: false
          COMMIT_MESSAGE: "Automated Coding Activity Update :rocket:"